### ISSUE TITLE
Zřízení testovacího prostředí ( ? hodin podle dělení práce)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#10]
Měli bychom se zamyslet nad způsobem nasazování nových verzí aplikace. Stávající varianta, kdy nutné testování vede k nestabilitě či nedostupnosti dat na produkčním serveru je nevyhovující. U AMČR se nám dobře osvědčil oddělený server (vč. dat, v tomto případě odděleného indexu), kde jsme můžeme aplikaci libovolně zkoušet, zasahovat do dat atd. Na produkci pak uvolňujeme oboustranně potvrzenou stabilní verzi. Např. dnešní situace, kdy se nedaří po úpravách vygenerovat náhledy, je problematická.

Prosím o návrh řešení, jak zajistit hladké nasazování oprav a úprav.

**Comment by albertoh** [comment]
Souhlasim.
Meli bychom mit dalsi server, schopen se dostat na data (vetsina problem vznikaji pri generovani nahledu)

**Comment by pavelkocourek** [comment]
Připravíte prostředí pro nasazení Testu? mezitím domluvíme rámec pravidel.

**Comment by motyc** [comment]
Mluvil jsem o tom s @MichalKminek - prostředí připravíme. Nevím ale, kdy přesně se to stihne. Zatím pojedeme ve stávajícím režimu, ale zkusíme to zajistit co nejdříve.

**Comment by lucka-pavlova** [comment]
Pro určení počtu hodin je potřeba upřesnit dělení práce mezi Alberta a p. Kmínka.
