### ISSUE TITLE
Nastavení počtu záznamů na dotaz

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#101]
Měli bychom patrně vracet na jeden dotaz více záznamů. Kolik je reálné 100? 1000? Budeme dávat jiná čísla pro dc/amcr/rdf či pro různé sety?

**Comment by vbar** [comment]
Myslím že 1000 by mělo být bez problémů... Na druhé straně současná implementace používá jediné číslo (konfigurační volbu) pro všechny formáty i sety, takže v tomto směru bych to pokud možno nekomplikoval...

**Comment by motyc** [comment]
Pokud všechny služby zvládnou 1000, pak dejte 1000. Případně uvažte jinou stabilní konfiguraci, pokud by se to ukázalo jako moc velký počet.
