### ISSUE TITLE
Pády tomcat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#103]
Po příkazu: https://api-test.aiscr.cz/dapro/oai?verb=ListRecords&set=dok_jednotka&metadataPrefix=oai_rdf

(před tím řada dalších prošla)

**Comment by vbar** [comment]
Pravděpodobně bylo způsobeno vyčerpáním paměti - zvýšil jsem povolenou velikost heapu Tomcatu (na 5 GB), a problém se přestal projevovat...
