### ISSUE TITLE
Špatné parsování URL

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#105]
Digiarchiv chybně parsuje URL. Pokud použiji tento odkaz, který vznikl pomocí filtrace v Digiarchivu, jeho opětovné užití vede ke špatně vyfiltrovaným výsledkům: https://digiarchiv.aiscr.cz/results?adv=heslar;lokalita_typ_lokality;and;nemovit%C3%A1%20pam%C3%A1tka;starts;nemovit%C3%A1%20pam%C3%A1tka&adv=heslar;komponenta_areal;and;hradi%C5%A1t%C4%9B;starts;hradi%C5%A1t%C4%9B

Jde o to, že se načtou podle daných atributů (v tomto případě "Lokalita - typ" a "Komponenta - areál") nikoli položky podle nastavení v URL (nemovitá památka, resp. hradiště), ale podle první položka v odpovídajícím hesláři.

**Comment by motyc** [comment]
Podivné je, že problém nastává jen někde - např. toto funguje dobře: https://digiarchiv.aiscr.cz/results?kategorie=foto&f_autor=Marounek,%20Ji%C5%99%C3%AD

**Comment by vbar** [comment]
Problém patrně nastává při asynchronním překladu, který nastavuje první položku z hesláře, bez ohledu na existující hodnotu - což samozřejmě nesmí... Přidána podmínka.

**Comment by pbartosova** [comment]
Připraveno do  releasu.
