### ISSUE TITLE
Doplnění loga v patičce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#106]
Prosím o doplnění přiloženého loga do patičky (po grafické úpravě, aby bylo v souladu s ostatními):

http://www.archeologickamapa.cz/images/logos/logo_09.png

Logo navázat na odkaz: http://av21.avcr.cz/

**Comment by motyc** [comment]
Šlo by prosím ještě u loga zaměnit bílou za šedou tak, aby mezi ostatními tolik nesvítilo a bylo ve stejné barvě jako ostatní?

**Comment by RadkaKittova** [comment]
@motyc To by určite šlo no free dostupné nástroje na zmenu farby v .png formáte nie sú tak kvalitné, aby to vyzeralo dobre a bez bielych škvrniek. Zmenu spravím doma na súkromnom počítačí, kde mám Adobe balíčky a zajtra dodáme novú verziu :)

**Comment by motyc** [comment]
Skvěle, díky. Klidně to tedy nasaďte, jak to je, a zítra už jen zaměníme logo.
