### ISSUE TITLE
Nejde se přihlásit

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#11]
Systém hlásí špatné údaje, i když jsou jistojistě dobře.

Prosím vyřešit rychle.

**Comment by albertoh** [comment]
Zmenili jste API?
V logach je error:
org.apache.xmlrpc.XmlRpcException: Incorrect parameters passed to method: Signature permits 6 parameters but the request had 4

To neni na me

**Comment by motyc** [comment]
Chyba je na straně SmartGIS (ověřil jsem), za chvilku sem hodím popis změny.

**Comment by motyc** [comment]
Podle SmartGIS je nově třeba přidat tyto dva statické parametry (proč, to se mne neptejte...):

![image](https://user-images.githubusercontent.com/20186892/34869689-f95ebe6c-f787-11e7-9a07-15ea24c81a2d.png)

**Comment by albertoh** [comment]
Zmeneno. Nazaseno. Nas ucet uz funguje

**Comment by motyc** [comment]
můj taky, díky za rychlé vyřízení
