### ISSUE TITLE
Problémy s indexací

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#120]
Indexace dokumentů se chová velmi podivně. Zjištěno po pátečním importu cca 650 foto do AMČR.:
1) Foto dosud nebyly indexovány, přestože jsou archivované (např. https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/C-DT-100005469&metadataPrefix=oai_amcr)
2) Ruční reindexace pomocí url_aplikace/indexer?action=FULL&clean=true vedla k načtení jiných než aktuálních dat (bylo sledovatelné na počtu textových dokumentů).
3) Během dvou dnů o víkendu (kdy žádné dokumenty nebyly archivovány!), se výrazně měnil počet dokumentů indexovaných v Digiarchivu.

Prosím o celkovou kontrolu a rychlou opravu procesu.

**Comment by pbartosova** [comment]
Zatím stále se pracuje analýze.

**Comment by motyc** [comment]
Nalezl jsem další příklad dokumentu, který není indexovaný, ale přitom nesouvisí s importovanou várkou: C-TX-201300783

**Comment by pbartosova** [comment]
Problém pravděpodobně nemá souvislost s hromadným importem. Řešení problému má vysokou prioritu. Probíhá analýza dat v databázi (cca 250 záznamů), zejména napojení na pian. Neprovádějte prosím žádný hromadný import, dokud se problém nevyřeší.

**Comment by motyc** [comment]
Potvrzuji, žádný další import dat nyní neplánujeme.

**Comment by pbartosova** [comment]
Problém nesouvisí s importem, ale je to následek situace, která způsobila i issue https://github.com/ARUP-CAS/aiscr-amcr/issues/63 a https://github.com/ARUP-CAS/aiscr-amcr/issues/64.
V tabulce dokument zůstal záznam s prázdným ident_cely, který se dostal do exportu.

**Comment by pbartosova** [comment]
Byla provedena reindexace, po půlnoci by se měla provést automatická indexace,který by měla potvrdit, že je vše v pořádku.
