### ISSUE TITLE
Chyba reindex - invalid char between encapsulated token and delimiter

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#13]
Může souviset s optimalizací exportů. Mělo by nyní platit, že oddělovačem polí je nyní skutečně jen # a pole není nikdy ohraničeno uvozovkami, i když obsahuje mezery atd. Pokud je # použit v datech, pak je na exportu změněn na [hash]. Ostatní speciální znaky nejsou nijak escapovány.

**Comment by motyc** [comment]
Celá hláška:
"error": "java.lang.RuntimeException: java.io.IOException: (line 11469) invalid char between encapsulated token and delimiter"
}}}

**Comment by motyc** [comment]
@albertoh @pavelkocourek Prosím toto celkem hoří, protože index je nyní prázdný - šlo by brzy vyřešit? Samozřejmě pokud to souvisí s úpravami API, není to bug na vaší straně...

**Comment by albertoh** [comment]
Pustim se do toho.
Ale urcite to bude zmenou v API. Najdu presne kde to vznika, a napisu zaplatu

**Comment by albertoh** [comment]
Reindexoovano.
Jsou tam chybi. Exportni program generuje souboru nespravne. Nektere radky nejsou komplektni.
[indexer_full.txt](https://github.com/ARUP-CAS/arup-da-amcr/files/1631884/indexer_full.txt)

**Comment by motyc** [comment]
Děkuji za zpracování. Zítra soubor s chybami projdu a zjistím příčiny.

**Comment by motyc** [comment]
Souvisí s tím, že vystup nyní vypadá takto?

**Comment by albertoh** [comment]
To vypada na zmenu exportnich souboru. Prozkoumam to.

**Comment by motyc** [comment]
Dvě změny o kterých vím:
- odstraněn sloupec "n_id" u akce
- odstraněn sloupec "organizace" u projektu

Ani jeden sloupec se neindexoval, respektive v Digiarchivu přímo nepoužíval.

**Comment by albertoh** [comment]
Opraveno
