### ISSUE TITLE
Speciální znaky - problémy s indexací

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#15]
> problem ve exportu je, ze nektere radky maji min sloupcu nez by mely
> napriklad akce
> [comment=null, mapping={ident_cely=0, okres=1, katastr=2, dalsi_katastry=3, uzivatelske_oznaceni=4, vedouci_akce=5, organizace=6, hlavni_typ=7, vedlejsi_typ=8, specifikace_data=9, datum_zahajeni=10, datum_ukonceni=11, datum_zahajeni_v=12, datum_ukonceni_v=13, lokalizace=14, poznamka=15, ulozeni_nalezu=16, je_nz=17, vedouci_akce_ostatni=18, organizace_ostatni=19, typ=20, stav=21, stav_popis=22, pristupnost=23, odpovedny_pracovnik_zapisu=24, odpovedny_pracovnik_autorizace=25, odpovedny_pracovnik_zamitnuti=26, odpovedny_pracovnik_archivace=27, odpovedny_pracovnik_archivace_zaa=28, odpovedny_pracovnik_vraceni_zaa=29, odpovedny_pracovnik_odlozeni_nz=30, odpovedny_pracovnik_podani_nz=31, datum_zapisu=32, datum_autorizace=33, datum_zamitnuti=34, datum_archivace=35, datum_podani_nz=36, datum_archivace_zaa=37, datum_vraceni_zaa=38, datum_odlozeni_nz=39}, recordNumber=12388, values=[C-201701582A, Semily, DALIM??ICE, , , Prost?edník, Jan, Muzeum Turnov, sonda, environmentální vzorek, p?esn?, 2017-07-20, 2017-08-07, 2017-07-20, 2017-08-07, Areál Agba, v.o.s.. Parc. ?. 968/40, P?i skrývce pro pilí? p?eloženého NN bylo registrováno v úrovni podorni?í 6 nemovitých objekt? (4 k?lové jámy, 1 sloupová jáma, objekt s linií 3 k?lových jamek). Objekty jsou vypln?ny tmav? šedou hlínou prachové konzistence s detekovaným biomateriálem. Na povrchu jsou patrné zcela zkorodované zlomky keramiky. Výpl? objekt? nese stopy vyloužení, ale pouze na okrajích. 20.7. a 21.7. prob?hla exkavace nemovitých objekt? a odb?r výpln? pro environmentální analýzy v?etn? C14.  Obj. 1/17 (0,6 x 0,8 m, mocnost 0,6 m, V profil, hladké st?ny, ploché dno d patrným negativem hrotu k?lu - pr?m?r 0,2) - sloupová jáma; obj. 2/17 (2,2 x 1,1 m, mocnost 0,2 m, nepravidelný ovál, nerovné dno, U profil - sídlištní jáma); obj. 3/17 (pr?m?r do 0,2 m, hloubka 0,3 m) -  k?lová jamka; obj. 4 a 5/17  (pr?m?ry do 0,2 m, hloubka 0, 4 -  0,5 m) - dvojice k?lových jamek; obj. 6/17 (pr?m?r do 0,2 m, hloubka 0,25 m) - k?lová jamka.]]
> konci driv
> a indexer neni schopen zpracovat sloupec "ulozeni_nalezu"

Není to bug, jen text obsahuje tag [new_line], který značí novou řádku. Proto se zdá, že to končí dříve. Data jsou ale v pořádku.

**Comment by albertoh** [comment]
Data nejsou v poradku.
Tam kde se to stava, pred [new_line} je skutecne konec radku.
Napriklad C-201701582A:

...kůlová jamka.
[new_line]Jde ve všech případech ...

Ale pozor, v prohlizece to neni videt. Je potreba otevrit v textovem editoru.

**Comment by motyc** [comment]
Díky, Jdu řešit se SmartGIS. Je zajímavé, že v našich exportech, které by měly být totožné to ani v notepadu ani v PSpadu nevidím...

**Comment by motyc** [comment]
Chyba nalezena a opravena, lze otestovat. Přidávám vysvětlení od Smart GIS:

> Některé operační systémy používají pro konec řádku kombinaci několika symbolů, které ale naopak jednotlivě používají zase jiné operační systémy.
> Tedy, zjednodušeně, v exportu u popsaného příkladu byla "polovina symbolu" pro nový řádek. V INCAD si toho všimli, protože data zpracovávají programově (nízkoúrovnově). V exportu pro administrátory AMČR se to chovalo shodně, ale tyto exporty se typicky otevírají v nějakém vysokoúrovňovém programu (např. excel), který podobné problémy odfiltruje už během otevření souboru a chyba se tak k uživateli ani nedostane.

**Comment by albertoh** [comment]
Reindexoval jsem. Zadne chyby nebyly. Muzeme zavrit.
