### ISSUE TITLE
Preklady heslaru - zobrazení překladů (1 hodina)

### ISSUE THREAD

**Issue by albertoh** [ARUP-CAS/arup-da-amcr#16]
Koukni na stary github
https://github.com/incad/arup-da-amcr/issues/132

**Comment by albertoh** [comment]
Procistil jsem kod. Zmenil jsem dok :)

**Comment by motyc** [comment]
Ještě:

1) chyba v hesláři nálezů - překládá se pouze polovina (předměty), ale nikoli ta druhá (objekty) - platí pro facetu i detail záznamu

![image](https://user-images.githubusercontent.com/20186892/36093874-4ecc3196-0fec-11e8-8f57-2e794804a68e.png)


2) chyba v typu dokumentu po rozbalení kategorie

![image](https://user-images.githubusercontent.com/20186892/36093939-90e5c1d2-0fec-11e8-9635-9d65bdf65359.png)


3) překlad areálu v detailu záznamu u komponenty

![image](https://user-images.githubusercontent.com/20186892/36094005-d1d8b46a-0fec-11e8-8b15-a45657e203c6.png)


4) Rozšířené vyhledávání - není přeloženo nic


5) Druhý typ akce

![image](https://user-images.githubusercontent.com/20186892/36094167-7783b2ca-0fed-11e8-953b-1930763cbd24.png)

**Comment by motyc** [comment]
Snad poslední problém - viz předchozí bod 1, jen v detailu záznamu u komponenty (stejné to bude i u komponent dokumentu - zkontrolovat):

![image](https://user-images.githubusercontent.com/20186892/37199208-41960aee-2381-11e8-9a7e-f59635690de0.png)

**Comment by lucka-pavlova** [comment]
Přesouvám na květen

**Comment by albertoh** [comment]
Chybi csv soubory v thesauri pro Okres a Organizace. Jinak mam dodelana ostatni pole

**Comment by motyc** [comment]
okres nepřekládáme (není jak), organizace dodám

**Comment by albertoh** [comment]
A muzeme generovat csv bez prekladu? Jinak mi chybi ten seznam

**Comment by motyc** [comment]
organizaci jsem dal na FTP

U těch okresů mi to přijde trošku zbytečné - vždyť např. katastry také nemáme jako heslář zvlášť. Pokud je to nutné, mohu to asi vyrobit, jen moc nevím, čím se to liší...

**Comment by motyc** [comment]
Už to vidím, je to kvůli tomu seznamu. Ok, dodám heslář.

**Comment by albertoh** [comment]
Jeste mi chybi soubor pro "rada"

**Comment by motyc** [comment]
doplněno na FTP

**Comment by motyc** [comment]
@albertoh heslář řada tam je, jen se nepřekládá do angličtiny

**Comment by albertoh** [comment]
Opraveno! Zapomnel jsem kopirovat konfiguraci...
