### ISSUE TITLE
Dokumentace (cca 2 hodiny)

### ISSUE THREAD

**Issue by albertoh** [ARUP-CAS/arup-da-amcr#17]
Nechat v konfiguraci jen polozky, ktere se realne pouzivaji pro zmeny nastaveni. Zbyle polozky odstranit a pripadne okomentovat v odpovidajici casti kodu (pro vyvojare).

Upravit popis, jak funguje lokalizace (původní postup již nyní neplatí).

**Comment by motyc** [comment]
@albertoh @MichalKminek - pánové prosím věnujte tento týden maximální prioritu dokončení dokumentace, tak abychom ji mohli přiložit jako podklad k výběrovému řízení. Nejpozději do poloviny února potřebujeme mít vše v pořádku a k dispozici. Díky

**Comment by motyc** [comment]
@MichalKminek prosím uveď sem, co ještě schází, aby byl jasný rozsah nutné práce.

**Comment by motyc** [comment]
Návštěva M. Kmínka byla realizována 13.4.2018.

@MichalKminek , lze issue uzavřít?

**Comment by MichalKminek** [comment]
Popis aplikací zde na WiKi byl přepracován a doplněn na základě podkladů z posledního sezení s Albertem. Aktuálně dokumentace plně odpovídá projektu.
