### ISSUE TITLE
Generování náhledů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#18]
V řešení staré známé chyby pokračujme zde.

Indexace náhledů možná doběhla, nicméně náhledy mnohdy stále chybí. Souvisí to s přeskakováním, nebo je problém jinde? Nebylo by dobré zkusit celé smazat a vygenerovat znovu, abychom poznali, co je chyba a co důsledek nějakých starších chyb?

Příklad je dokument C-TX-200201375 a mnoho dalších.
![image](https://user-images.githubusercontent.com/20186892/35273776-0c90f97c-003a-11e8-8ecd-8df5854af763.png)

**Comment by motyc** [comment]
Doplňuji, že se netýká jen PDF, ale i fotek, kde by s náhledy neměl být (a nebyl) problém.

**Comment by albertoh** [comment]
Nasel jsem chybu v cestach. Opraveno.

**Comment by motyc** [comment]
Ok, zobrazení jen bílých stránek u některých dokumentů (např. CTX200100109) souvisí s velikostí stránek?

**Comment by motyc** [comment]
Nalezl jsem další dokumenty s nevygenerovanými stránkami, např.:

![image](https://user-images.githubusercontent.com/20186892/36095598-22605874-0ff3-11e8-8fc3-e993792743f1.png)

**Comment by albertoh** [comment]
Bile stranky jsou zpusobene formatem JPEG2000. Soubor CTX200100109.pdf je obsahuje.
Posledni problem nevygenerovane stranky jiz je vyresen (zase cesty)

**Comment by motyc** [comment]
Budeme dělit mezi menší konkrétní issues.
