### ISSUE TITLE
Malé náhledy chyba

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#19]
Objevila se nová chyba v malých náhledech u detailu - místo zmenšeniny se zobrazuje levý horní roh.
![image](https://user-images.githubusercontent.com/20186892/35691785-c13a4982-0779-11e8-8f2e-7ac0df25217d.png)

**Comment by albertoh** [comment]
Chyba odstranena

**Comment by motyc** [comment]
Malé náhledy se již zobrazují, jen se nám to nyní graficky nějak rozpadlo (každý je jinak velký, zvláště u leteckých fotek to nevypadá dobře). Prosím o doladění s Petrem do původní (nebo jiné estetičtější) formy...
