### ISSUE TITLE
Jména - zobrazování a facety

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#2]
V některých polích se jmény může být jmen více. Vždy platí, že jsou oddělena středníkem bez mezery. Pro zobrazování těchto polí by měl být středník vždy doplněn o mezeru (za středníkem). Pro vyhledávání (fasety) by měl být středník chápán vždy jako oddělovač a jména by měla být chápána zvlášť, jako jednotlivé výskyty.

**Comment by motyc** [comment]
Ještě drobná chybka v zobrazení. Proč navíc Stoklásková není ve facetě?
![image](https://user-images.githubusercontent.com/20186892/35692076-9ee8de1a-077a-11e8-8c14-e7e7bca69756.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
rozdělení jmen v facetě je ok

v textu v uvedeném příkladu je teď čárka místo středníku (měl zůstat středník) a není za ní mezera (ta měla přibýt) - výsledek bude: Hůrková, Jindra (Muzeum Klatovy); Tetour, Michal; Stoklásková, Lucie (Muzeum Klatovy)

**Comment by albertoh** [comment]
je to tam
