### ISSUE TITLE
Indexace chyba - urgentní

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#23]
Indexace hlásí chybu a nedoběhne:

"error": "org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/relations: missing content stream"

**Comment by albertoh** [comment]
Pridam do indexeru moznost preskocit tabulku prazdnou, a pustim reindex.
Ale obavam se, ze tim padem, dokumenty by mohli byt neuplne.

**Comment by albertoh** [comment]
Odkaz

**Comment by motyc** [comment]
Tak ta byla prázdná vždy. Zatím jsme tam nic neimportovali a v tomto nebyla žádná změna
