### ISSUE TITLE
Seznam používaných služeb API (cca 2 hodiny)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#24]
Prosím o soupis služeb AMČR API, které jsou v praxi užívány Digiarchivem. Je třeba jej předat do SmartGIS, aby zajistili včasné informování o možných dopadech změn.

**Comment by albertoh** [comment]
Mam to napsat tady na wiki, nebo mailem?

**Comment by motyc** [comment]
Založ prosím ve Wiki novou stránku. Díky.

**Comment by motyc** [comment]
@MichalKminek v souvislosti s poslední úpravou #17 jsi patrně odstranil rubriku vzniklou na základě tohoto issue. @albertoh máme někde zálohu?

**Comment by motyc** [comment]
Omlouvám se, nalezeno jinde ve struktuře. Opět zavírám.
