### ISSUE TITLE
C-TX-200100620 - je vidět malý náhled, nikoli však stránky uvnitř (1 hodina zkoumani logu)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#25]
![image](https://user-images.githubusercontent.com/20186892/37201496-2c2b6e22-2388-11e8-8d19-1aef993ff22d.png)

**Comment by lucka-pavlova** [comment]
Neni jasne jestli jde o chybu aplikace nebo selhání prostředí. Alberto bude cca 1 hodinu zkoumat logy, z toho vyplyne další postup.

**Comment by lucka-pavlova** [comment]
Prosim otestovat jestli po regenerovani je uz v poradku.
