### ISSUE TITLE
C-TX-200001341 - dokument se dříve načítal včetně obsahu, nyní bílé stránky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#26]

**Comment by albertoh** [comment]
Opravil jsem ten konkretni dokument. K tomu jsem pustil ThumbnailsGenerator takto:
java -Xmx3g -Damcr_app_dir=/var/lib/archeo/amcr/ -jar ThumbnailsGenerator-1.0.jar -id CTX200100620.pdf

Zadnou zmenu jsem nedelal, a ted jsou videt obrazky korektne. A i pred tim dve posledni stranky take byly v poradku.
 Hledam v logach, jestli najdu co se stalo. zatim nevidim zadnou chyby

**Comment by lucka-pavlova** [comment]
merge #25 , jde o stejny problem
