### ISSUE TITLE
Doplnit podmínku pro generátor náhledů (1 hodina)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#27]
Přeskakovat dokumenty jejichž ID začíná na "X-"

**Comment by albertoh** [comment]
Pridano.

**Comment by motyc** [comment]
Díky, otestuji.

**Comment by lucka-pavlova** [comment]
Je možné tohle issue zavřít?

**Comment by motyc** [comment]
Ano, z různých důvodů se mi to špatně testovalo, ale podle potřeby se k tomu případně vrátíme.
