### ISSUE TITLE
Při přepínání mezi soubory jednoho dokumentu prohlížečka přeskakuje na špatné stránky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#29]
Pokud má dokument více souborů, já listuji jedním souborem a poté překliknu na druhý, není druhý soubor od začátku ale od nalistované stránky v prvním souboru, i když v počítadle je napsaná strana 1.

![image](https://user-images.githubusercontent.com/20186892/37495649-7666033c-28ae-11e8-900e-de995f778ee6.png)

**Comment by lucka-pavlova** [comment]
Jde o bug, Alberto bude zkoumat příčinu.
