### ISSUE TITLE
Generování náhledů - chybějící položky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#31]
I přestože generování náhledů bylo dokončeno (již se spouští jen periodicky dokola), nevygenerovaly se některé náhledy a nejsou uvedeny ani mezi "skipped" ani mezi "unprocessables".

Jde o řadu leteckých snímků (namátkou C-DL-200200017) a terénních fotek (např. DT-C-200912970A-00001). Myslím, že bude chyba v algoritmu pro přeskakování již hotových náhledů.

Chybí ale i náhledy pro textové dokumenty (např. C-TX-200100023).

**Comment by lucka-pavlova** [comment]
Jde o bug, Alberto bude zkoumat příčinu.

**Comment by albertoh** [comment]
Je to tak, algoritm pro preskakovani pocital s tim, ze identifikatoru jsou unikatni. Ale unikatni jsou filepath.
Opraveno. Novy jar je na serveru, pri pristim behu by mely se generovat chybejci nahledy.
