### ISSUE TITLE
Skrývání dokumentů bez náhledu (cca 16 hodin)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#33]
Ve výchozím nastavení nezobrazovat dokumenty, které nemají náhled. Tuto funkci bude možno vypnout přepínačem pod facetami, s popiskem: "zahrnout dokumenty bez náhledu".

**Comment by lucka-pavlova** [comment]
Přesouvám na květen.

**Comment by albertoh** [comment]
Pridal jsem pri indexovani dokumentu nove pole pro zohledneni pritomnost nahledu.
Jako nahled rozumim ten maly, ktery zobrazujeme v seznamu vysledku. Ne testuju pritomnost vsech obrazku (to by bylo prilis velke zdrzeni indexace)
 Tim padem, v indexu bude aktualni stav tohoto pole v momentu indexace. Pokud se prida pozdeji nahled, dokument by se mel reindexovat.
 K tomuto ucelu jsem pridal novou akci v servletu indexer:
 indexer?action=INDEX_DOKUMENT&id=ident_cely_dokumentu

Mimochodem, po zkoumani indexu vyplyva, ze nechybi zadny nahled v dokumentech. Ovsem v tech, ktere hledame v aplikaci, tj s podminkami
       rada nemuze byt za nebo zl
       stav musi byt 1  nebo 3

**Comment by motyc** [comment]
Díval jsem se na to a podle mne tam někde musí být chyba, protože např. u C-TX-201800136 se mi náhled nezobrazí a mimochodem se mi nezobrazí ani vazba na související archivovanou akci. Nejsem si jistý, zda to souvisí s touto úpravou, nebo s něčím jiným. Podobně např. s dokumentem C-DD-201800001.

![image](https://user-images.githubusercontent.com/20186892/40542312-fc0f9c98-601f-11e8-8edc-a5a9239ed4b9.png)

**Comment by motyc** [comment]
A ještě prosím o drobnost - posuňme zaškrtávací pole nad facety a také by to chtělo nějak vyladit, aby řádek, ve kterém checkbox je, měl stejné marginy jako nadpisy facet

**Comment by albertoh** [comment]
To jsem nenapsal, kdyz dokument nema pripojene soubory, ukazujeme. Podminka o nahledu je neplatna v tom pripade. 
 Muzu to zmenit, ale zda se mi logicky.
 Nedelal jsem zmenu v logice indexace, co se tyce akce.

Checbox posunu na horu

**Comment by albertoh** [comment]
Nemuzu najit vazbu mezi akci "C-201662541A" a dokumentem "C-TX-201800136"...
Jsi jist?

**Comment by motyc** [comment]
Tak to je nějaké podivné, protože zmíněné dokumenty soubor mají a vazbu v AMČR také vidím, a to i v exportovaných CSV (export mám z 18. 5.), ale nepředpokládám změnu.

Jinak když by nebyl připojený soubor, pak je to samozřejmě v pořádku a logika je správně.

**Comment by albertoh** [comment]
Koukam, v indexu posledni indexace probehla pred mesicem.
Pustim reindex (bez zmazani)

**Comment by albertoh** [comment]
Reindexovano. Uz jsou tam akce.
http://digiarchiv.amapa.cz/results?showWithoutThumbs=true&q=%22C-TX-201800136%22

**Comment by motyc** [comment]
Bezva, já myslel, že jsi reindexoval... Díky, uzavřeno.
