### ISSUE TITLE
Přechod na protokol HTTPS

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#34]
Prodiskutujeme. Do budoucna by bylo vhodné.

**Comment by MichalKminek** [comment]
Aktualne mame sluzby digiarchiv-test.aiscr.cz:443 a digiarchiv.aiscr.cz:443 puvodni http weby jiz obsahuji pouze redirect/prepis

**Comment by MichalKminek** [comment]
Od nynejska je potreba pouzivat pouze tyto HTTPS varianty v dokumentaci a komunikaci. Puvodni domenu amapa podrzime nekolik nasledujicich let. Casem muzeme redirect z amapa nahradit strankou s upozornenim na konec domeny amapa.cz
