### ISSUE TITLE
Z kódu serverové aplikace vyjmout servlet ThumbsGenerator ( 2 hodiny)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#36]
Z kódu serverové aplikace bude kompletně vyjmut servlet ThumbsGenerator a místo něj bude funkce zalogování jména souboru, pokud na něj někdo přistoupí a nebude pro něj existovat náhled.

**Comment by lucka-pavlova** [comment]
Kdy chcete realizovat? Prosím přidejte milestone.

**Comment by motyc** [comment]
Přidáno. Uděláme v květnu.
