### ISSUE TITLE
U dokumentu se nezobrazují informace o letu a tvaru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#39]
U leteckých snímků se nezobrazují data z DT "Let" a "Tvar". V rozšířeném vyhledávání přitom "tvar" odpovídajícím způsobem vystupuje, otázka je, nakolik je do vyhledávání implementována třída "let".

Zde přikládám původní soubor se zadáním (listy Data, Zobrazení a Vyhledávání): 
[DA_strukura_zaznamu_160617_test_161019.xlsx](https://github.com/ARUP-CAS/arup-da-amcr/files/2110432/DA_strukura_zaznamu_160617_test_161019.xlsx)

Zde je původní zadání formy zobrazení (viz část "Popis letu", která by měla vypadat podobně jako "Popis dokumentu" a "Tvary (příznaky) na letecké fotografii", která by měla vypadat podobně, jako komponenty):
[DA_detail_zaznamu_160906.docx](https://github.com/ARUP-CAS/arup-da-amcr/files/2110438/DA_detail_zaznamu_160906.docx)

**Comment by albertoh** [comment]
reindexovano, pridano
