### ISSUE TITLE
Nevyhledává se v nálezech dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#42]
I přestože letecké fotografie mají komponentu dokumentu a zapsané nálezy dokumentu, neobjevuje se faceta "druh nálezu", tak jak tomu je v jiných případech. Období a areál tam přitom jsou.

Pravděpodobně ani rozšířené vyhledávání s nálezy dokumentu nepracuje, i když podle zadání má.

**Comment by vbar** [comment]
IMHO metoda CSVIndexer.getNalezDokumentu v průběhu indexace nic nenajde (a tedy žádné nálezy nezaindexuje), protože CSVIndexer.getKomponentaDokumentu ji volá se špatným parametrem - ID jednotky dokumentu místo očekávaného ID komponenty dokumentu.

**Comment by motyc** [comment]
To zní logicky, prosím tedy pokud možno o opravu.
