### ISSUE TITLE
Po nahrání nových dat se objevila nová kategorie ve facetách, která tam nemá být

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#45]
Po reindexu nových dat je ve facetách položka "pivot.kategorie." s podpoložkou "mapa". To by ale měla být podkategorie položky "Plány a mapy" 
![image](https://user-images.githubusercontent.com/20186892/43902555-b0c0a8c0-9bea-11e8-92bd-5dafac0e5ff0.png)

**Comment by vbar** [comment]
Podle mně je to protože některé nové dokumenty mají typ "mapa", ke kterému není v konfiguraci (pod klíčem "kategoriet") přiřazena kategorie - takže dostanou prázdnou a zařadí se špatně...

**Comment by motyc** [comment]
Díky za radu. Doplnil jsem do konfigurace + reindex a vyřešeno.

**Comment by vbar** [comment]
Ono je celkově problematické když je konfigurační soubor závislý na hesláři v databázi... Přesouvat tu mapu do databáze by asi bylo příliš radikální, ale mohli bysme implementovat méně striktní - např. že všechny typy dokumentu začínající slovem "data" mají kategorii "ddata", "plán" nebo "mapa" má "mplany" apod. Pak by se ta konfigurace nemusela aktualizovat tak často - co o tom soudíte?

**Comment by motyc** [comment]
Celá situace vznikla vlastně změnou v hesláři, který je jinak velmi stabilní. Běžně do něj nezasahujeme a když teď už vím, kde změnu udělat, není problém při změně konfiguraci upravit. Myslím, že nestojí moc za to věnovat tomuto sílu, protože to jde poměrně snadno držet pod kontrolou. Mám obavu, že podobná pravidla nejde stanovit úplně generálně a spíše by to v budoucnu mohlo přinést obtíže.

**Comment by vbar** [comment]
OK, tak to necháme tak jak to je.
