### ISSUE TITLE
Nepřekládají se některá užití [new_line] na odřádkování.

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#48]
![image](https://user-images.githubusercontent.com/20186892/44268877-1ee29e00-a233-11e8-9f5b-5a9b8ba71d88.png)

**Comment by vbar** [comment]
Opraveno (a nasazeno na testu), ale pouze pro tento specifický případ - obávám se že stejný problém bude i na dalších místech...

**Comment by motyc** [comment]
Na testu nemohu ověřit, protože tam nemám kontrolu na daty. Nicméně prosím nasaďte to i na produkci, poté potvrdím.

Zkuste se také prosím zamyslet nad nějakým generálním řešením. Obecně by se k záměnně měly v textech objevovat jen řetězce [new_line] a [hash].
