### ISSUE TITLE
Skloňování slova výsledek a chybějící překlad.

### ISSUE THREAD

**Issue by RadkaKittova** [ARUP-CAS/arup-da-amcr#49]
Při počtu výsledků 1 - 4 má slovo výsledků stále stejný tvar (červený rámeček). Navrhuju změnu ve stejném  tvaru jako i Počet lokalít: (zelený rámeček). Pak by místo **1** výsledků, bylo: Výsledků: **1**, nebo Počet výsledků: **1** , (to už by bylo na Vás).. Nezáležalo by pak, jaké číslo bude zobrazeno, tvar slova by byl stále taký jistý.
<img width="952" alt="chyba_vysledek" src="https://user-images.githubusercontent.com/29093071/44651199-f30ca880-a9e8-11e8-8926-998e9749f3c1.PNG">

Dále není definovanej překlad v prvních dvou větách při nalezení 0 výsledků (červený rámeček). 
<img width="953" alt="chyba_preklad" src="https://user-images.githubusercontent.com/29093071/44651448-b7261300-a9e9-11e8-9669-ba7b729add0b.PNG">

**Comment by motyc** [comment]
1) souhlasím a přikláním se k variantě "Počet výsledků: ..."
2) dobrý postřeh, prosím o opravu
