### ISSUE TITLE
Automatizovat proces reindexace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#50]
Nastavit automatické vymazání a obnovení indexu na denní bázi, a to na čas např. kolem 3:00,
V době reindexu by měl Digiarchiv automaticky upozorňovat na nedostupný obsah, aby uživatelé (jakkoli nepravděpodobní) nebyli zmatení. Bylo by také vhodné nějak umět reagovat na chybu reindexu, a to buď opětovným spuštěním, nebo obnovou posledního funkčního indexu.

**Comment by vbar** [comment]
Automatické upozorňení na nedostupný obsah není tak složité přidat (zkoušel jsem nahradit vyhledávací pole varováním - to se projeví na domovské stránce i většině ostatních). Na druhé straně opakovat reindexaci po chybě je problematické (v řadě případů opakování nepomůže, např. když došlo místo na disku, a obecně bych to radši opakoval ručně a pozoroval projevy problému), zatímco rollback je komplikovaný - Solr není transakční databáze a žádnou takovou funkčnost nemá (aspoň pokud vím), takže bysme to museli implementovat nějak vedle, a garantovat transakční sémantiku není jednoduché...

**Comment by motyc** [comment]
Ok, přidejte tedy varování. Ono by asi stačilo, kdyby tam i při chybě nějaké to varování zůstalo a zároveň aby někdo byl automaticky upozorněn, že to má řešit. Bylo by špatné, kdyby indexace spadla a pak tam několik dní visel chybný stav... Zbytek argumentace chápu a souhlasím, že to můžeme nechat být.

**Comment by vbar** [comment]
Varování moc dlouho zůstat nemůže (respektive ne moc jednoduše), protože je jen v paměti. Tomcat klidně může restartovat kdykoli uzná za vhodné (pravděpodobně to neudělá v průběhu zpracování HTTP dotazu, ale na víc bych nespoléhal), a Digitální archiv momentálně nemá žádné zapisovatelné úložiště (samozřejmě i webová aplikace může psát na disk, ale je to třeba synchronizovat, a nerad bych se dostal do problémů které má se synchronizací Archeologická mapa), takže perzistentním chybovým stavům bych se pokud možno vyhnul... Automatické upozornění bych přidal do skriptu vyvolávajícího indexaci - ten už dostává JSON s popisem chyb, takže ho může rozparsovat, a když najde nějakou chybu poslat e-mailem. Otázka je komu - existuje nějaký e-mailový účet přijímající automatické notifikace o chybových stavech Digitálního archivu, případně Archeologické mapy? Ideálně by měl přeposílat na mailing list, aby si je mohli přihlásit noví zájemci bez nutnosti změny aplikace...

**Comment by vbar** [comment]
Po zralé úvaze, existuje ještě jedna možnost jak zabránit prázdné databázi při chybě: nevyprazdňovat databázi před zahájením indexace. Čas od času se databáze Digitálního archivu vyprázdnit musí, aby se odstranila zastaralá data, ale dá se to dělat s podstatně menší frekvencí než přidávání nových dat (případně pouze ručně, ale spíš bych automatizoval obě možnosti, aby se na tu méně častou nezapomínalo)...

**Comment by motyc** [comment]
Děkuji za návrhy, myslím, že nalézáme řešení:
- ad mail - zatím takový není, ale zřídíme jej a začneme to tam posílat; prozatím tam cvičně můžete dát přímo můj (novak@arup.cas.cz) a až to bude připravené (nová adresa), změníme jej
- ad update - ano, to není špatný nápad; ono by to asi stačilo promazat  jednou týdně (např. při nedělním/pondělním ranním reindexu); mohlo by to možná být i méně často, ale pak by se např. neprojevovala (nebo až s velkým zpožděním) změna přístupnosti dokumentů, která je nyní rovněž automatizovaná na denní bázi a jsou tam i další důvody, proč frekvence nemůže být moc nízká; i tak, ale pravděpodobnost chyby snížíme a budeme to vždy moct v pondělí zčerstva řešit, když k něčemu dojde

**Comment by motyc** [comment]
Při pohledu do kódu mne napadla ještě jedna drobnost - email pro odesílání chybových hlášek bych raději vystavil jako klíč, který bude nastavitelný v interní konfiguraci na serveru. Není dobré, aby šlo o přímou součást kódu. Co myslíte?

**Comment by vbar** [comment]
Tak ano, je to možné, akorát se při změně bude muset editovat konfigurace serveru, což má to samé riziko jako editace skriptu (tj. že se editací rozbije), akorát ne pouze pro skript, ale i pro server... Momentálně se dá e-mail změnit z příkazové řádky (tedy na produkci editací konfiguračního souboru cronu) - to nestačí?

**Comment by motyc** [comment]
On není takový problém, jak to měnit, ale že součástí kódu na GitHub je konkrétní email, který je odvislý od konkrétní instalace aplikace. Pokud to někdo nebude vědět a část kódu by převzal, dost pravděpodobně tam ten email zůstane. Pokud je nějaké "bezpečnější" řešení, pak jej navrhněte. Za sebe bych viděl ideální, že výchozí hodnota bude "null" (maily tedy nechodí), která se přepisuje klíčem z config.json pro konkrétní server. Pokud klíč nebude, nebo bude špatně, pak se nestane nic horšího, než že emaily nebudou chodit. Nebylo by to řešení?

**Comment by vbar** [comment]
OK, implementoval jsem. Klíč je "recipient" ve struktuře "amcrapi".

**Comment by motyc** [comment]
Výborně, Jinak už je připravená adresa reporting@amapa.cz, která slouží jako alias pro rozeslání mně, Vám a paní Jindrákové. Pokud byste tam chtěl někoho přidat, dejte mi vědět.

Lze releasovat, config uprvím, jen mi Michal musí změnit uživatelská práva na FTP. Nějak jsme s tím laborovali a mám teď config.json jen ke čtení...

**Comment by vbar** [comment]
OK, nasadil jsem. Nepřístupnost config.json je patrně důsledkem mého editování - jaký má být vlastník toho souboru?

**Comment by motyc** [comment]
Děkuji. Soubor je pod root, ale já tam přistupuji jako tomcat. To si ale vyřešíme interně. Vlastnictví jako takové je asi správně, jen já nemám dost oprávnění...
