### ISSUE TITLE
I když se k dokumentu váže více PIAN, v mapě se zobrazuje jen jeden

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#51]
Zde by měly být P-2211-000220 a P-2211-010013. Vidím však jen první.

![image](https://user-images.githubusercontent.com/20186892/44991444-56bc4600-af94-11e8-8ccf-673fac0aab2d.png)

**Comment by vbar** [comment]
Data pro 2 PIANy se fakticky posílají do browseru, ovšem komponenta mapy zobrazuje pouze jeden - to se dá opravit, akorát to vede k tomu že když se jeden PIAN přidá do filtrů (tj. otevře a klikne se na jeho link), zůstanou na mapě oba - předpokládám že to není očekávané/žádoucí chování?

**Comment by motyc** [comment]
Není to sice úplně ideální, ale nevadí to nijak závažně a je to lepší varianta, než ta stávající.

**Comment by vbar** [comment]
Fakticky by neměl být takový problém aby mapa respektovala filtrování podle PIANu - pak se defaultně ukážou všechny, a po vybrání pouze ten vybraný.

**Comment by motyc** [comment]
Fajn, pakt to tedy prosím takto implementujte. Hlavní je ale dořešit ten výše popsaný problém, kdy je vidět pouze jeden, i když jich má být vidět více.

**Comment by motyc** [comment]
Na testu nemohu plně ověřit, protože tam nejsou vhodná data, resp. možná jsou, ale neumím je najít. Zkusím na plné verzi.
