### ISSUE TITLE
Nelze otevřít soubor u záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#58]
http://digiarchiv.amapa.cz:8080/id/C-LD-000000176
po kliknutí na foto se nic nestane

**Comment by vbar** [comment]
Akce selhává, protože ta fotografie nemá správně metadata. Opravil jsem v databázi (pro CLD000000176.tif - je možné že ten samý problém mají i další soubory), po reindexaci by kliknutí mělo fungovat.

**Comment by motyc** [comment]
Děkuji za vysvětlení. Bude tedy třeba toto řešit na úrovni AMČR a podívat se, proč metadata vznikají špatně. Zakládám novou chybu v evidenci pro AMČR a tento bug zavírám.

**Comment by vbar** [comment]
AMČR server nevyplňuje rozsah u obrázků, u kterých se dá předpokládat že jsou jednostránkové. Import dat (případně až frontend) musí s tímto případem počítat a nevyplněný rozsah interpretovat jako 1.

**Comment by pbartosova** [comment]
Opraveny i data v databázi s releasem AMČR 5.9.5

**Comment by motyc** [comment]
Viz telefon. Nejsem si jistý, zda pan Bárta nechtěl v archivu situaci vyřešit tak, aby při návratu "null" byl Digiarchiv schopen se s takovou hodnotou vyrovnat. Pokud to nemá smysl (nebo je to hotové), pak to klidně uzavřeme.

**Comment by vbar** [comment]
Asi by to dávalo smysl ošetřit i v digiarchivu - AMCR nastavuje rozsah na více místech, a nejsem si úplně jist že jsem přidal default všude...

**Comment by motyc** [comment]
Pardon, zavřeno omylem. Ok, souhlas, doplnění bude vhodné.
