### ISSUE TITLE
Refresh mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#59]
Pokud provedu libovolný výběr, poté otevřu mapu a poté použiji persistentní odkaz, kde si opět zobrazím mapu, mnohdy nedojde k refreshi a mapa obsahuje původní data a správná poloha se načte až po čase. Podobně je tomu i při jiných změnách ve filtraci/přechodech mezi obrazovkami. Je třeba zajistit, aby v mapě data byla vždy aktuální, nebo bylo zřejmé, že se dosud nenačetla.

**Comment by pbartosova** [comment]
Chybu eviduji a při první přiležitosti na ni budeme pracovat.

**Comment by vbar** [comment]
Přidáno vyčištění mapy při změně URL.
