### ISSUE TITLE
Obnovení stránky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#6]
Někdy se stává, že se stránka neobnoví a jen se pomalu nahoře sune progress bar. V takové chvíli pomůže až návrat na home page a aktualizace stránky. Obvykle je to ve chvíli, kdy rychleji za sebou měním filtrace a odebírám filtry z drobečkové navigace. Občas se i u mapy stává, že tam zůstává již neplatné zobrazení, které neodpovídá aktuálnímu výběru. Potřeba doladit.

Zde příklad:
![image](https://user-images.githubusercontent.com/20186892/32170778-45cb40a0-bd76-11e7-98f8-a78dae1abb32.png)

**Comment by albertoh** [comment]
Nedari se mi to zreprodukovat.
Mam podezrene, ze to souviselo s tim, jak byl tomcat ve spatnem stavu pri generovani nahledu nez jsme pridali samostatni proces

**Comment by albertoh** [comment]
Zaviram. Otevreme pokud zase uvidime

**Comment by motyc** [comment]
Tak bohužel jsem nasimuloval velmi rychle. Asi by bylo dobré to ukázat přes Skype nebo něco podobného...

**Comment by albertoh** [comment]
Zkus to znovu, plz

**Comment by motyc** [comment]
Zdá se být dobré, díky.
