### ISSUE TITLE
Nepřekládají se některé položky do angličtiny

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#62]
Jde o:
- položku tvary, ale jen v rámci záznamu (v rozšířeném vyhledávání je to dobře)

![image](https://user-images.githubusercontent.com/20186892/48906622-5f226f80-ee65-11e8-92c9-690fabc836b7.png)

- o položku organizace (překládá se opět jen v rozšířeném vyhledávání)

![image](https://user-images.githubusercontent.com/20186892/48906690-98f37600-ee65-11e8-9f26-50c23d17388d.png)

- položku druh lokality (pouze faceta)

![image](https://user-images.githubusercontent.com/20186892/48906939-5c744a00-ee66-11e8-94e8-34a1b668dceb.png)

**Comment by vbar** [comment]
Nasazení oprav bude vyžadovat změnu konfiguračního souboru na serveru, specificky odstranění klíče "facets" / "translate", aby se použilo nastavení z konfigurace zabalené do aplikace - tohle asi není část konfigurace kterou by bylo třeba upravovat za běhu...

**Comment by motyc** [comment]
Danou část konfiguračního souboru jsem odstranil.

**Comment by motyc** [comment]
Aha, tak já tam vrátím zálohu toho souboru, co jsem si udělal a pak to upravte podle potřeby.

**Comment by vbar** [comment]
OK

**Comment by vbar** [comment]
Produkční konfigurace aktualizována.
