### ISSUE TITLE
Chyba indexace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#64]
Pravidelně se při indexaci objevuje takováto chyba (ne na stejném záznamu, ale stejného typu):

`{"message": {
  "clean": {"message": "Index cleaned"},
  "full": {
    "translations": {
      "obdobi_druha.csv": {
        "docs indexed": 135,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "tvar.csv": {
        "docs indexed": 16,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "ulozeni_originalu.csv": {
        "docs indexed": 7,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_akce_druha.csv": {
        "docs indexed": 19,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "aktivity.csv": {
        "docs indexed": 10,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "okres.csv": {
        "docs indexed": 77,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "predmet_kategorie.csv": {
        "docs indexed": 19,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "rada.csv": {
        "docs indexed": 15,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "specifikace_objektu_druha.csv": {
        "docs indexed": 97,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "druh_lokality_druha.csv": {
        "docs indexed": 21,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "zeme.csv": {
        "docs indexed": 1,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_dokumentu.csv": {
        "docs indexed": 38,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_udalosti.csv": {
        "docs indexed": 5,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "ellapsed time": "00:00:02",
      "specifikace_predmetu.csv": {
        "docs indexed": 63,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "objekt_druh.csv": {
        "docs indexed": 152,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_sondy.csv": {
        "docs indexed": 10,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "docs indexed": 1256,
      "zachovalost.csv": {
        "docs indexed": 6,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "errors msgs": [],
      "nahrada.csv": {
        "docs indexed": 5,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "pristupnost.csv": {
        "docs indexed": 5,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_lokality.csv": {
        "docs indexed": 3,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "jazyk_dokumentu.csv": {
        "docs indexed": 7,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "predmet_druh.csv": {
        "docs indexed": 203,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "format_dokumentu.csv": {
        "docs indexed": 11,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "posudek.csv": {
        "docs indexed": 30,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "dohlednost.csv": {
        "docs indexed": 3,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "pocasi.csv": {
        "docs indexed": 4,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "material_dokumentu.csv": {
        "docs indexed": 25,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "typ_dj.csv": {
        "docs indexed": 5,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "objekt_kategorie.csv": {
        "docs indexed": 16,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "areal_druha.csv": {
        "docs indexed": 67,
        "ellapsed time": "00:00:00",
        "errors": 0
      },
      "errors": 0,
      "organizace.csv": {
        "docs indexed": 181,
        "ellapsed time": "00:00:00",
        "errors": 0
      }
    },
    "error": "java.lang.IllegalArgumentException: The header contains a duplicate name: \"139402663942590.zip\" in [, C-201442590, 139402663942590.zip, 139402663942590.zip, , 2017-06-01, application/zip, 561747, 1496307699841_139402663942590.zip]"
  }
}}`

Indexace nedoběhne, ale druhá re-indexace (nově spuštěná) pak proběhne vždy v pořádku.

**Comment by motyc** [comment]
viz #74 - budeme dále sledovat

**Comment by motyc** [comment]
Tak se hned na prvním pokusu ukázalo, že toto s #74 nesouvisí a jde o samostatný problém. Důležitý je poslední řádek, kde dochází k nějakému konfliktu názvů. Nevím, jestli to nesouvisí s tím, že se třeba po prvním zavolání "indexer?action=FULL&clean=true" index vymaže neúplně a napodruhé už je to pak dobré. Opět je potřeba vyřešit kvůli #50

**Comment by pbartosova** [comment]
Ok, chybu převezme vbar.
