### ISSUE TITLE
Přidat informaci o CC-BY-NC

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#65]
Bude třeba doplnit do zápatí v této podobě:
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Licence Creative Commons" style="border-width:0; vertical-align: middle; padding-right: 10px" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a>&nbsp;<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Dataset" property="dct:title" rel="dct:type">Databáze Archeologická mapa ČR</span>, jejímž autorem je <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.arup.cas.cz/" property="cc:attributionName" rel="cc:attributionURL">Archeologický ústav AV ČR, Praha, v. v. i.</a> a <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.arup.cas.cz/" property="cc:attributionName" rel="cc:attributionURL">Archeologický ústav AV ČR, Brno, v. v. i.</a>, podléhá licenci <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní (CC BY-NC 4.0)</a>. Užití dat i metadat podléhá této licenci, pokud není explicitně stanoveno jinak.

A anglicky:
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Licence Creative Commons" style="border-width:0; vertical-align: middle; padding-right: 10px" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a>&nbsp;<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Dataset" property="dct:title" rel="dct:type">Database Archaeological Map of the Czech Republic</span>, authored by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.arup.cas.cz/" property="cc:attributionName" rel="cc:attributionURL">Institute of Archaeology of the CAS, Prague, v. v. i.</a> and <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.arub.cz/" property="cc:attributionName" rel="cc:attributionURL">Institute of Archaeology of the CAS, Brno, v. v. i.</a>, is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)</a>. Re-use and sharing of data and metadata is covered by this license, unless explicitly stated otherwise.

**Comment by vbar** [comment]
Při té příležitosti bysme mohli přidat i logo Space Systems Czech...

**Comment by motyc** [comment]
Ano, souhlasím, nicméně jej prosím zaměňte za logo Search Technologies. Log už je tam hodně, a budeme to brát jako logo aktuálního správce. Spojte to také prosím s #70

**Comment by vbar** [comment]
OK

**Comment by motyc** [comment]
Funkčně je to skvělé, jen by to chtělo o něco málo lépe napozicovat. Upravil bych to celé takto (souvisí také s #70:
![image](https://user-images.githubusercontent.com/20186892/52702931-87f66480-2f7d-11e9-84a3-fb70f205503a.png)

**Comment by vbar** [comment]
OK, přesunul jsem.
