### ISSUE TITLE
Aplikace pro kontrolu přístupových práv

### ISSUE THREAD

**Issue by vbar** [ARUP-CAS/arup-da-amcr#66]
Bude implementována jako Tomcat servlet s jednou API metodou vracející pro uživatele a jeho heslo (vyžaduje nasazení na HTTPS) jeho úroveň oprávnění. V první fázi budou převzaty uživatelské účty AMČR (vyžaduje spojení do databáze), poté bude implementována jejich konverze do nového schématu (ve stejné databázi).

**Comment by vbar** [comment]
API bude na URL <code>https://&lt;servername&gt;/pass/check</code> (jméno serveru bude specifikováno podle požadavků na síťovou konfiguraci). API není verzované - případné nekompatibilní změny mohou být řešeny pozdější změnou URL (přidáním verze). Jedinou podporovanou přístupovou metodou bude HTTP POST; GET není žádoucí, protože GET dotaz by musel obsahovat heslo jako URL parametr. Vstupní i výstupní data API budou ve formátu JSON. Vstup má schéma
<pre>
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "user",
    "pwd"
  ],
  "properties": {
    "user": {
      "$id": "#/properties/user",
      "type": "string",
      "examples": [
        "user@example.com"
      ],
      "pattern": "^(.+)$"
    },
    "pwd": {
      "$id": "#/properties/pwd",
      "type": "string",
      "examples": [
        "secret"
      ],
      "pattern": "^(.+)$"
    }
  }
}
</pre>

Výstup (při úspěšné autentizaci)

<pre>
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "auth"
  ],
  "properties": {
    "auth": {
      "$id": "#/properties/auth",
      "type": "string",
      "examples": [
        "B"
      ],
      "pattern": "^[A-E]$"
    }
  }
}
</pre>

a pro neznámého uživatele/neplatné heslo

<pre>
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "error"
  ],
  "properties": {
    "error": {
      "$id": "#/properties/error",
      "type": "string",
      "examples": [
        "unknown"
      ],
      "pattern": "^unknown$"
    }
  }
}
</pre>

Ostatní chyby API budou hlášeny chybovými kódy HTTP (např. 400 Bad Request pro neplatný JSON).

**Comment by motyc** [comment]
@vbar souhlas

**Comment by pbartosova** [comment]
Nasazeno na DEV.
