### ISSUE TITLE
Řazení hesláře kultur v rozšířeném vyhledávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#67]
Heslář se má řadit podle pole "poradi", nikoli abecedně.

**Comment by pbartosova** [comment]
Ok, chybu evidujeme.

**Comment by vbar** [comment]
Hesláře digitálního archivu (v adresáři thesauri) pole "poradi" sice nemají, nicméně se zdá že jsou už řazené - jak se vlastně ty soubory vytvářejí? Pokud respektují "poradi" v databázi, mělo by stačit aby se je frontend přestal pokoušet řadit a použil implicitní pořadí...

**Comment by motyc** [comment]
Ty soubory vytvářím ručně, protože je to momentálně jediný způsob, jak tam dostat anglické verze hesel. Pokud tedy bude respektováno pořadí v souborech csv, pak to je dobré řešení a nemám s ním problém. Na testu to teď vypadá v pořádku.
