### ISSUE TITLE
Nepřekládají se filtrace podle nálezů v drobečkové navigaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#68]
![image](https://user-images.githubusercontent.com/20186892/50726233-80d07100-110a-11e9-9f02-3b63906e12a1.png)

**Comment by pbartosova** [comment]
Ok.  Situaci nejdříve zopakuji, a pak dám vědět.

**Comment by vbar** [comment]
Přidána konfigurace překladů pro druh nálezu a organizaci.
