### ISSUE TITLE
Upravit logo

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#70]
Vyměnit logo ARÚP v zápatí za toto (pozor, je bílé, je třeba kliknout...):

![arup](https://user-images.githubusercontent.com/20186892/50846826-554ec000-1370-11e9-8329-62cc49ce1fd9.png)

**Comment by motyc** [comment]
Loga se nyní zarovnávají k horní hraně a vypadá to zvláštně. Prosím o úpravu tak, aby zarovnávaly vertikálně na střed nebo úpravu log tak, aby  byla stejně vysoká.

**Comment by motyc** [comment]
viz též #65:
![image](https://user-images.githubusercontent.com/20186892/52703007-abb9aa80-2f7d-11e9-814e-585bca195099.png)

**Comment by vbar** [comment]
OK, posunul jsem.

**Comment by motyc** [comment]
Logo ARÚ Praha je deformované.

**Comment by vbar** [comment]
Defaultně se nastavuje špatná velikost, stále nechápu proč - nicméně vhodnou kombinací extra atributů jsem to snad potlačil...
