### ISSUE TITLE
Začít používat správu release

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#71]
Začít zde na GitHub používat správu release s changelogy. Prozatím vývoj probíhal poměrně živelně a bylo by dobré, aby u projektu zůstávala odpovídající evidence release.

Založil jsem nyní release v1.0.0 a od něj bychom se měli odrážet dále.

**Comment by vbar** [comment]
Je to číslo release někde v gitu? Jak se bude zvyšovat? Sémantické verzování a podobné algoritmy jsou spíš pro moduly než webové stránky... A jak si představujete changelog - prostě seznam zapracovaných tiketů?

**Comment by motyc** [comment]
Měl jsem na mysli užívat tuto funkci na GitHubu: https://github.com/ARUP-CAS/arup-da-amcr/releases

V podstatě je to velmi formální záležitost, kdy lze stručně popsat, co nový release mění, přidat číslo verze a změny oproti předchozímu by se měly samy vysledovat. Nevím, jestli máme oba na mysli totéž...

Jinak bych to dělal tak, že vždy po otestování a schválení daného stavu kódu se udělá nový release, který se nasadí na produkci. Nebo něco přehlížím? Přijde mi to poměrně přímočaré...

**Comment by vbar** [comment]
No v zásadě máme na mysli totéž, akorát jsem nevěděl že GitHu pro to má podporu...
