### ISSUE TITLE
U letů se nezobrazují některá pole

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#73]
"dohlednost" doplnit do položky "Podmínky:" do závorky za počasí.
"hodina_zacatek"-"hodina_konec" doplnit do závorky do položky "Datum (hodina):"

**Comment by pbartosova** [comment]
Ok, chybu eviduji.

**Comment by vbar** [comment]
Opraveny podmínky pro zobrazování dohlednosti a hodiny. Fotoaparát se nezobrazuje patrně protože byl odstraněn ze zdrojových dat.

**Comment by motyc** [comment]
Na testu potvrzuji. S fotoaparátem máte pravdu, ve skutečnosti tam ten údaj vyplněný nikdy nebyl. Má chyba.

**Comment by vbar** [comment]
Já tedy mám dojem že jsem ho ("Nikon") kdysi viděl, ale v produkční databázi teď nikde vyplněný není...

**Comment by motyc** [comment]
To byla testovací data. Díval jsem se do importů a skutečně tam nic není...
