### ISSUE TITLE
Problém s indexací

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#74]
Při pokusu o reindexaci Digiarchiv hlásí chybu a indexace nedoběhne:
"error": "java.lang.RuntimeException: java.io.IOException: Premature EOF"
![image](https://user-images.githubusercontent.com/20186892/52150782-47d7dd80-2671-11e9-921b-cfc13e14d115.png)

**Comment by motyc** [comment]
Zajímavé je, že to vždy skončí jindy (zkoušel jsem opakovaně).

**Comment by vbar** [comment]
Problém vypadá na chybu CSV exportovaného z archeologické mapy, ale v separátně exportovaném CSV nejsou žádné chyby vidět... Upravil jsem indexaci, aby CSV nejdřív stáhla (do dočasného souboru v adresáři /var/cache/tomcat/temp ), a parsovala ze souboru. Zajímavé je, že po této změně indexace proběhla bez chyb; bude-li se problém opakovat, budeme mít vstupní data a můžeme pokračovat v ladění...
