### ISSUE TITLE
Velmi nekvalitní náhledy obrázků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#77]
V případě některých náhledů (např. http://digiarchiv.amapa.cz/id/M-FT-110598800) je obraz extrémně nekvalitní. Bylo by možné nějak optimalizovat nastavení generátoru, aby lépe odpovídaly skutečnému snímku a pouze se snížila velikost snímku v px na požadovanou úroveň? Takto jsou některé náhledy téměř nepoužitelné.

**Comment by pbartosova** [comment]
Ok. Podívám se, jak se vytvářejí náhledy a co by s tím šlo udělat.

**Comment by motyc** [comment]
Ještě dodávám, že problém se zdá být zejména u obrázků ve stupních šedi. Barevné vypadají překvapivě mnohem lépe.

**Comment by pbartosova** [comment]
Neuvedl byste nějaké odkazy, které jsme si ukazovali, když jsme issue probírali? Tato ukázka není úplně katastrofální, hodil by se nějaký extrémní příklad.

**Comment by motyc** [comment]
To má prozaický důvod - černobílé foto jsem ručně předělal/nahradil.

Příkladem budiž třeba tento dokument: https://digiarchiv.aiscr.cz/id/C-TX-192000023 (srovnejte si nahled s originalem). Lépe je to ale vidět na čb foto.

**Comment by vbar** [comment]
Aha, takze obrazek

![1551985214937_MFT110598800 tif_medium](https://user-images.githubusercontent.com/108574/59688221-8d8ae200-91dd-11e9-86cd-94b781318dc6.jpg) 

je to co thumbnail generator normalne generuje?

**Comment by motyc** [comment]
Ano, to se mi zdá být jako ono.

**Comment by vbar** [comment]
On by si asi měl generátor všimnout že zmenšuje šedivý obrázek a nepřidávat do něj barvy, jenže existující implementace používá vysokoúrovňovou knihovnu, která patrně na takové podmínky nemá interface...

**Comment by motyc** [comment]
Chápu. Také mi přišlo mi, že to vlastně celé mění ze stupní šedi do modra. Pokud nebude jiné řešení, asi tedy bude třeba knihovnu vyměnit za nějakou vhodnější (pokud tedy nejde upravit pro naše potřeby).

**Comment by vbar** [comment]
Tak nakonec se interface našel - thumbnail generator na testu by nyní měl generovat

![1551985214937_MFT110598800 tif_medium](https://user-images.githubusercontent.com/108574/59764788-ca69de00-929c-11e9-9206-8d074d25af03.jpg)

(tedy, kdyby byl v testovacích datech zdroj toho obrázku, což není - náhled byl vytvořen ručně). Ještě se podívám na ty pdf...

**Comment by motyc** [comment]
Skvěle, to vypadá velmi dobře. U PDF to myslím bude podobný problém. Je také otázka, jak velká je tam výchozí komprese JPEG. Pokud je to možné, ponechal bych ji někde na 80 % a pod tuto hodnotu bych nechodil.

Vzhledem k tomu, že na testu toho v tomto případě moc neotestuji, asi to pak nasaďte na produkci. Bohužel dalším krokem pak bude náhrada všech dosavadních náhledů, ale naštěstí to nejde tak pomalu. To už si ale zařídím sám.

**Comment by vbar** [comment]
U PDF byl problém, že se náhled generoval příliš malý a potom zvětšoval... Nasadil jsem a přegeneroval https://digiarchiv.aiscr.cz/id/C-TX-192000023 - vypadá o poznání lépe...

**Comment by motyc** [comment]
Skvěle, to je mnohem lepší.
