### ISSUE TITLE
Mapování XML->RDF

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/arup-da-amcr#79]
Prosím dokončit chybějící části.

**Comment by motyc** [comment]
Pracuji na tom dnem i nocí. Už zbývá jen kousek a bude to hotové, snad dnes.

**Comment by motyc** [comment]
Tak už se to pomalu rýsuje, ale hotový ještě nejsem. Zabředl jsem do různých nepoznaných zákoutí, ale výsledek zatím vypadá velmi funkčně. Přikládám X3ML a RDF, které by mělo vzniknout při stávajícím stavu jako výsledek. Zcela hotové jsou projekty, po dokumentační jednotku je to v pokročilém stavu a od dokumentu dále je na tom ještě více práce. Zjistil jsem také, že mi chybí unikátní ID pro nálezy, bez kterého je trošku problém udělat správný výstup, možná tedy bude třeba do vstupního XML přidat ještě jedno pole (resp. dvě - pro nálezy a nálezy dokumentu). Obdobné to bude i s tvary. Teoreticky by se to ale asi dalo nahradit i tím UUID generátorem. To ale zjistím, až budu hotov... Pro testování by přiložené soubory měly bohatě stačit. Pokračovat budu snad zítra, ale finální verzi budu mít asi až po neděli.

[X3ML_190314.ZIP](https://github.com/ARUP-CAS/arup-da-amcr/files/2964455/X3ML_190314.ZIP)

**Comment by vbar** [comment]
Bylo by možné rozdělit to mapování do více souborů - jeden pro projekty, druhý pro dokumentační jednotky apod.? Myslím že už je to dost velký soubor aby se ho vyplatilo udržovat po částech, a hlavně se obávám aby ho skousl X3ML engine - zkoušel jsem pustit přechozí verzi na dump projektů, a neskončil ani za 48 hodin... Dokumentace říká ře náročnost zpracování stoupá s počtem vstupů krát počtem pravidel, takže bzch se snažil nezahrnovat do ní pravidla která se nikdy neuplatní (tj. mapping dokumentačních jednotek pro projekty a naopak)...

**Comment by motyc** [comment]
Teoreticky by to možné bylo. V principu to jde rozdělit na jednotlivé části podle tagu <mapping>. Tyto části 1:1 odpovídají dílčím částem XML exportu. To je ostatně viditelné z prvního tagu <source_node> hned za <domain>. Musela by se jen replikovat hlavička X3ML a zrušit globální proměnné. Ale 48 hodin je tedy síla. Otázka je, zda v první verzi nejsou problém i ty UUID, které se musí automaticky generovat. Když to tady bude nastavené konstantně, mohlo by to být jednodušší.

Zde přikládám pokusnou osekanou verzi jen pro projekty: [AMCR_to_CIDOC_X3ML_projekty.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2967488/AMCR_to_CIDOC_X3ML_projekty.zip)

**Comment by vbar** [comment]
Já bych řekl že se to prostě někde zaseklo - pokud se to bude opakovat i na finální verzi, budeme to muset zkusit odladit (nebo ideálně by to mohli zkusit odladit autoři X3ML enginu, ale jsem skeptický kolik práce budou chtít věnovat cizímu projektu), a samozřejmě pro ladění taky potřebujeme co nejmenší jak mapping, tak vstupní XML...

**Comment by motyc** [comment]
Zde je konečně finální mapping včetně verzí pro dílčí části: [AMCR_to_CIDOC_X3ML_190319.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2985700/AMCR_to_CIDOC_X3ML_190319.zip)

Omlouvám se, že to tak trvalo, ale ukázalo se to podstatně komplikovanější, než se zdálo. Myslím ale, že nyní snad vše funguje, jak má. Další zásahy ani zde dělat nebudu, dokud se na nich společně nedohodneme. Úpravy budou nutné v případě doplnění druhého jazyka pro heslářové položky. Nyní jsou v EN a CS všechny popisky.

**Comment by motyc** [comment]
V souvislosti se změnou v exportu XML přidávám i aktualizaci mappingu: [AMCR_to_CIDOC_X3ML_190408.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3054866/AMCR_to_CIDOC_X3ML_190408.zip)

Změny souvisí s úpravami popsanými v #81 + jsou odstraněny položky s osobními údaji z mappingu projektů.

**Comment by pbartosova** [comment]
Finální verze mapping. Změněn název souboru pro pian a vnitřní tag pian. Viz domluva u #81.
[AMCR_to_CIDOC_X3ML_mapping_final.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3206409/AMCR_to_CIDOC_X3ML_mapping_final.zip)
