### ISSUE TITLE
URL Generation policy

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/arup-da-amcr#80]
Prosím o dodání.

**Comment by motyc** [comment]
Na tomto zapracuji hned, jakmile dodělám vlastní mapování.

**Comment by motyc** [comment]
[AMCR_Generator_Policy.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2961387/AMCR_Generator_Policy.zip)

Zde zasílám generator policy, která mi zatím dostačuje. Nevylučuji ještě drobná doplnění, ale zdá se, že to možná nebude třeba.

**Comment by motyc** [comment]
Zde je aktualizovaná verze: [AMCR_Generator_Policy_190314.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2964459/AMCR_Generator_Policy_190314.zip)

**Comment by motyc** [comment]
Nejnovější verze odpovídající dnešnímu X3ML: 
[AMCR_Generator_Policy_190319.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2985690/AMCR_Generator_Policy_190319.zip)
