### ISSUE TITLE
Export dump databáze do XML.

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/arup-da-amcr#81]
Komponenta zajišťuje export dump databáze do XML.
Schéma požadovaného xml předáno.
Bude součástí serveru, tj. php skript.

**Comment by pbartosova** [comment]
Hotové projekty.

**Comment by vbar** [comment]
Rovněž akce, lokalita, let a dokumentační jednotka. Dokument je exportován částečně.

**Comment by motyc** [comment]
Nezapomenout prosím ve výsledných XML escapovat z dat speciální znaky, které jsou nekompatibilní s XML.

**Comment by motyc** [comment]
Zde je aktualizovaná verze exportu. Musel jsem tam kvůli fungování X3ML vrátit některá pole odkazující na parent. Zároveň bylo nutné doplnit u některých prvků pole `<pom_id>`, kam buď lze uložit id z databáze, nebo stačí i generovat přírůstkovou řadu na úrovni exportu. Potřebuji nějak jednoznačně odlišit jednotlivé instance a toto byl jediný způsob. Další zásahy již neplánuji, pokud se na tom společně nedohodneme.

[AMCR_XML_mapping_190319.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/2985666/AMCR_XML_mapping_190319.zip)

**Comment by motyc** [comment]
Přikládám novou verzi vzoru pro export, kde byly provedeny dvě změny:
1) Na základě naší schůzky jsem podle dohody upravil výstup tak, že v xml nebudou emaily uživatelů, ale jen jména příjmení
2) Do projektu jsem doplnil geometrii lokalizace projektu (tagy `<geometry_e>` a `<geometry_n>`), kterou máme v API pro NPÚ a zde by nám chyběla. Díky tomu bude možné původní API zcela zrušit.

[AMCR_XML_mapping_190408.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3054815/AMCR_XML_mapping_190408.zip)

**Comment by pbartosova** [comment]
_Projekt_ - done (issue prázdných řádků při spojení Jméno Příjmení)
_Akce_ - dodělat odmazání emailů
_Dokumentační jednotka_ - done
_Dokument_ - done
_Ext_zdroje_ - doplnit externí odkazy
_Let_ - done
_Lokalita_ - dodělat odmazání emailů
_Pian_ - dodělat odmazání emailů
_Soubor_ - done

**Comment by pbartosova** [comment]
TODO: Sjednotit názvy exportu a souborů s sql příkazem.

**Comment by motyc** [comment]
Přeskakovat položky v "Soubor" pokud `<dokument>` is null

**Comment by vbar** [comment]
Aktualizováno podle AMCR_XML_mapping_190408, přidáno datum do dokumentační jednotky (podle issue #89), doplněna struktura uvnitř dokumentu a externího zdroje, odfiltrovány soubory bez dokumentů. Zbývá exportovat stav projektu jako číslo, plus jsem si všiml že v exportu PIAN je obsah geom_gml quotovaný - to je záměr? Klienti si ho asi mohou odquotovat zpátky na XML, ale když už ho PostgreSQL vrací jako XML, a exportuje se uvnitř XML, připadalo by logičtejší nechat ho jako XML...

**Comment by motyc** [comment]
Ad GML - není to záměr, dával bych to sem nequtované... Asi to bylo kvůli CSV

**Comment by pbartosova** [comment]
Je možné přejmenovat tag pro PIAN na pian, aby vše bylo jednotně malými písmeny. Odpovídá to i setu pian #99 .

**Comment by motyc** [comment]
Ano, není problém.

**Comment by pbartosova** [comment]
Mapování bylo doplněno o stav popř. přístupnost pro dok_jednotka, soubor a pian.

[AMCR_XML_mapping_1900520.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3197858/AMCR_XML_mapping_1900520.zip)

Stejná úprava je nutná i pro rdf #79

**Comment by motyc** [comment]
Myslím, že pro RDF to není potřeba doplňovat, že to stačí na exportech fo XML. Pro transformaci do RDF to stejně budeme vždy filtrovat na základě XML a teprve poté transformovat již profiltrované (jako by se na to vždy díval anonym).

**Comment by pbartosova** [comment]
Otázkou je, zda si s tím poradí X3ML Engine. Ten na vstupu dostane tagy, pro které nebude mít mapping. Musíme ověřit.

**Comment by motyc** [comment]
Takové tam už jsou v předchozí verzi (např. údaje o oznamovateli). Pokud to tedy funguje nyní, neměl by to být žádný problém.

Díval jsem se do mappingu XML a mám drobnou poznámku - dokumentační jednotky je tam jen ve verzi pro akci (chybí tagy `<parent_lokalita>` a `<lokalita_stav>` - je to omyl nebo záměr?

**Comment by pbartosova** [comment]
Upravovala jsem původní soubor a tam byl jen tento případ.
Naimplementováno je to tak, že se vyhledají navázané akce a lokality pro DJ, pokud výsledek obsahuje nějaká data, vypíší se, pokud se nic nevyhledá, řádek se vynechá.

Až budou exporty na TESTu prosím o kontrolu.

Ještě musíme najít způsob, jak sofistikovaně otestovat, že se k pianům správně přiřazuje přístupnost a že se nevypisují piany, které nejsou na nic navázané.

**Comment by motyc** [comment]
No, ve skutečnosti jste oproti původnímu odmazala tag `<parent_lokalita>`. Myslím, že by to mělo vypadat takto:

[AMCR_XML_mapping_190520.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3198057/AMCR_XML_mapping_190520.zip)

Pak to samozřejmě ještě prokontroluji. Ty PIAN také nějak vymyslíme, testovací data půjdou udělat.

**Comment by pbartosova** [comment]
Ano, máte pravdu, ten řádek jsem omylem smazala. Přiznávám se. :) Do složky shared je nahrán správný dokument, ten od Vás)

**Comment by pbartosova** [comment]
Dočasné projekty se tedy neexportují viz #89 .
Jsou ještě nějaké požadavky na eliminaci při exportu? (např. u Dokumentů, Akcí)

**Comment by motyc** [comment]
Ne, nejsou, toto by měla být už poslední věc v daném ohledu.
