### ISSUE TITLE
Změna zobrazení persistentních odkazů kvůli přechodu na HTTPS

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#82]
V souvislosti s přechodem na novou doménu pod HTTPS (#34) bude třeba upravit zobrazení automaticky generovaných persistentních odkazů tak, aby se zobrazovaly správně. 
Původní: http://digiarchiv.amapa.cz/id/C-TX-192000018
Nový: https://digiarchiv.aiscr.cz/id/C-TX-192000018

Překlad jako takový je zajištěn (tj. původní odkazy budou i nadále funkční).

![image](https://user-images.githubusercontent.com/20186892/54218216-6db49580-44ed-11e9-832f-5356c6afa59c.png)

**Comment by vbar** [comment]
To by mělo stačit změnit v konfiguraci...

**Comment by motyc** [comment]
A jaký je to atribut? Nikde to nevidím, tak nevím, jak parametr nastavit... Myslíte var/lib/archeo/amcr/config.json (resp. ty configurace, které lze tímto souborem nastavovat)?

**Comment by vbar** [comment]
"serverUrl", ve slovníku "client", na hodnotu "https://digiarchiv.aiscr.cz" - on ve /var/lib/archeo/amcr/config.json dosud není (používá se zabudovaný), ale měl by zabrat...

**Comment by motyc** [comment]
Zkusil jsem doplnit, ale neprojevilo se. Zabere to až po reindexu, nebo hned?

![image](https://user-images.githubusercontent.com/20186892/58884038-e50a5780-86df-11e9-8ca5-6464c5cb5bd3.png)

**Comment by vbar** [comment]
Ne, jen je třeba restartovat servlet - teď jsem to udělal...
