### ISSUE TITLE
Data Provider RDF

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/arup-da-amcr#85]
Komponenta získá RDF od komponenty X3ML Engine a provede transformaci do oai-pmh.

**Comment by vbar** [comment]
Výstup X3ML Engine budeme nejspíš cachovat, tj. komponenta amcr-dapro si ho přečte z disku. Transformace do RDF je netriviální - X3ML Engine patrně poběží několik hodin, což se nedá spouštět na požádání...

**Comment by motyc** [comment]
To určitě není problém. Data klidně můžou být v tomto formátu poskytována s jistým zpožděním, tady jednotky dní nehrají roli. Možná by šel RDF výstup cashovat i s nějakou nižší periodou, třeba jednou měsíčně, pokud se to ukáže jako příliš náročné. Když to uživateli řekneme, nemůže nám to mít za zlé. Pokud bude alespoň jedno API dávat data zcela aktuální, resp. max den staré (ideálně #87, tedy "naše" XML), pak to je úplně v pohodě.

**Comment by motyc** [comment]
@vbar zde je odkaz na RDFS: http://www.cidoc-crm.org/sites/default/files/cidoc_crm_v5.0.4_official_release.rdfs

To by mělo podle mne mělo jako strojově čitelná specifikace stačit, ne?

**Comment by vbar** [comment]
RDFS je sice strojově čitelné, ale OAI-PMH vyžaduje XML Schema ( viz https://www.w3.org/XML/Schema ), které pro CIDOC CRM patrně neexistuje... Na RDFS samozřejmě můžeme odkázat, např. z našeho generického schematu, ale obávám se že celkovou specifikaci formátu data provideru žádný stroj automaticky nepřečte...

**Comment by motyc** [comment]
Rozumím, pak tedy připravte, co je třeba a na RDFS jen odkážeme.
