### ISSUE TITLE
Minimální filtrace pro všechna API

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#89]
Přemýšlel jsem nad nutnými filtracemi nad daty poskytovanými pro jakékoli API a vyšla mi tato tři nepřekročitelná kritéria, která nějak musíme zohlednit:
1) filtrace na základě procesního stavu
2) filtrace na základě přístupnosti záznamu
3) zobrazení/nezobrazení osobních údajů (částečně souvisí s oběma předchozími)

Jako "nice to have" bych přidal ještě datum archivace, případně i jiných změn stavů, ale to už pro začátek není tak podstatné.

Prosím zamyslete se, jak to řešit. Jako nouzová varianta mi přijde data filtrovat již při exportu do XML. Vznikaly by tak dílčí bloky/soubory pro jednotlivé skupiny dat, takže API by pak již jen bralo ty správné, které mají být danému uživateli při daném dotazu k dispozici.

Poptávka pro stahování dat, které se změnily po nějakém datu.

**Comment by motyc** [comment]
Pokud v tom nenajdete nějaký háček, vyřešil jsem celkem elegantně náš problém s filtrací podle data - stačí v rámci DT brát vždy to nejmladší datum z logu stavů.

Ve specifikaci níže jsme ponechal jen ta pole, která se mají brát v úvahu. Tam, kde je pole jen jedno, tak je to jasné. V ostatních případech se vezme vždy jen nejvyšší datum (myšleno nejmladší) a tím pádem bude datum záznamu skutečně odrážet na denní bázi záznamy, které se změnily, a to jakýmkoli způsobem. Snad taková agregace nebude problém, ale stejně bychom něco podobného museli u akcí řešit tak jako tak...

Jediný problém je s DT let, což je položka u které datum vztažitelné k evidenci chybí. Použijeme tedy prozatím datum letu.

[AMCR_XML_mapping_190408_datum.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3163701/AMCR_XML_mapping_190408_datum.zip)

**Comment by pbartosova** [comment]
Přihlášené projekty s dočasným X- nemají žádné datum, pouze datetime_born, chceme tyto záznamy filtrovat?

**Comment by motyc** [comment]
Já jsem to explicitně zapomněl zmínit, ale tyto projekty bych z XML exportu úplně vyřadil, protože ještě nedošlo k jejich finálnímu schválení a jde v podstatě o interní data ARÚ.

**Comment by pbartosova** [comment]
Soubor nemá identifier jako ostatní objekty, které pole pro jeho identifier chcete použít?

**Comment by motyc** [comment]
Už se mne na to ptal pan Bárta v #97, použijte prosím filepath.
