### ISSUE TITLE
Logování dotazů do API

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#92]
Počítá se v rámci API s nějakým logem dotazů, kde by bylo zřejmé kdo se ptal (IP) + dotaz? Pokud ne, budeme log potřebovat už kvůli GDPR.

**Comment by vbar** [comment]
Ano, logování řeší Tomcat - např. na amc-test jsou logy ve /var/lib/tomcat7/logs. IP a URL je v souborech localhost_access_log.* .

**Comment by motyc** [comment]
Skvěle, děkuji za odpověď, zase tedy zavírám.
