### ISSUE TITLE
OAI.PMH: Identify

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/arup-da-amcr#93]
Zvažte prosím požadavky na obsah odpovědi pro IDENTIFY.
http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify

**Comment by motyc** [comment]
Podívám se na to blíže a zašlu pokyny.

**Comment by motyc** [comment]
Pokud se dohodneme na druhé variantě ohledně #97, tak zde by měla být správná specifikace pro Identify. Pokud v #97 zvolíme první variantu, musela by se část `<description>` smazat nebo upravit.

**Comment by motyc** [comment]
@pbartosova Ještě jsem soubor v předchozím příspěvku nyní aktualizoval, pokud jste si jej stahovala dříve, prosím použijte až stávající verzi.

**Comment by motyc** [comment]
Zde tedy finální verze po dohodě nad #97 

[Identify.zip](https://github.com/ARUP-CAS/arup-da-amcr/files/3190825/Identify.zip)

**Comment by vbar** [comment]
OK, přidáno.
