### ISSUE TITLE
ListMetadataFormats

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/arup-da-amcr#98]
V tagu `<metadataFormat>` by myslím podle specifikace neměly být žádné další argumenty, nyní je tam zbytečně definice několika namespaces.
(viz http://www.openarchives.org/OAI/openarchivesprotocol.html#ListMetadataFormats)

**Comment by vbar** [comment]
Specifikace (konkrétně XML Schema) neomezuje namespace deklarace (pouze kde se smějí použít), ale je pravda že jsou tam zbytečně - odstranil jsem.
